#Updated game version settings.
#Thu Apr 24 12:54:42 BRT 2025
enable_iptables_tab=true
enable_ip_whitelist=false
enable_addons_tab=true
game_version=173
enable_character_list=true
enable_char_list=true
