#!/bin/bash

# Function to display usage
usage() {
  echo "Usage: $0 [path]"
  echo "  path      Directory path to change to (required)"
}

# Check if no argument is provided, display usage and exit
if [ -z "$1" ]; then
  usage
  exit 1
fi

# Change directory to the specified path
cd "$1" || { echo "Error: Unable to change directory to $1"; exit 1; }

# Run the command after changing the directory
./gamedbd gamesys.conf importrole temp.xml
rm temp.xml
pkill -9 gamedbd
{ ./gamedbd gamesys.conf & } &> /dev/null